name: portalcmj4
services:
  cmj4redis:
    image: redis:bookworm
    container_name: cmj4redis
    restart: always
    labels:
       NAME: "cmj4redis"
    volumes:
      - c4redis_data:/data
    #ports:
    #  - "6379:6379"
    networks:
      - cmj4-net
  cmj4solr:
    image: solr:9.7
    restart: always
    command: bin/solr start -c -f
    container_name: cmj4solr
    labels:
        NAME: "cmj4solr"
    volumes:
      - c4solr9_data:/var/solr
      - c4solr9_configsets:/opt/solr/server/solr/configsets
    ports:
      - "127.0.0.1:8983:8983"
      - "127.0.0.1:9983:9983"
    networks:
      - cmj4-net
  cmj4front:
    build:
      context: ../../.
      dockerfile: _docker/dev/Dockerfile.Dev.Front
    restart: no
    container_name: cmj4front
    labels:
       NAME: "cmj4front"
    volumes:
      - ../../.:/var/cmjatai/cmj4
    networks:
      - cmj4-net
    ports:
      - "127.0.0.1:5173:5173"
  cmj4:
    build:
      context: ../../.
      dockerfile: _docker/dev/Dockerfile.Dev
    container_name: cmj4
    labels:
      NAME: "cmj4"
    restart: no
    environment:
      DEBUG: 'True'
      USE_SOLR: 'True'
      SOLR_COLLECTIONS: portalcmj4_cmj,portalcmj4_arq
      SOLR_URL: http://solr:solr@cmj4solr:8983
      IS_ZK_EMBEDDED: 'True'
      TZ: America/Sao_Paulo
    volumes:
      - /mnt/volumes/cmj_media:/var/cmjatai/cmj_media
      - ../../.:/var/cmjatai/cmj4
    depends_on:
      - cmj4front
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - cmj4-net
networks:
  cmj4-net:
    name: cmj4-net
    driver: bridge

volumes:
  c4solr9_data:
  c4solr9_configsets:
  c4redis_data:
